steps:
  - id: "ls"
    name: alpine
    args: ['ls']

  - id: "Go build"
    name: "gcr.io/cloud-builders/go"
    args: ["build"]
    env: ["GOPATH=./src"]

  - id: "Go test"
    name: "gcr.io/cloud-builders/go"
    args: ["test"]
    env: ["GOPATH=./src"]