steps:
  - id: "Go build"
    name: "gcr.io/cloud-builders/go"
    args: ["build", "sum"]
    env: ["GOPATH=."]

  - id: "Go test"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "sum"]
    env: ["GOPATH=."]